# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ortfodb < Formula
  desc "A readable, easy and enjoyable way to manage portfolio databases using directories and text files."
  homepage "https://ortfo.org"
  version "1.4.0"
  license "MIT"

  depends_on "ffmpeg"
  depends_on "gifsicle" => :optional
  depends_on "imagemagick"
  depends_on "poppler" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ortfo/db/releases/download/v1.4.0/ortfodb_Darwin_x86_64.tar.gz"
      sha256 "584f5431b07ad3faae11ed9844a83c9bc21d4fae5dcbd4f63f6e6fcc45c2fe48"

      def install
        bin.install "ortfodb_darwin_amd64"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ortfo/db/releases/download/v1.4.0/ortfodb_Darwin_arm64.tar.gz"
      sha256 "bf7f10718b6db0cc4dbea91c916b06512f8d079deb84b33e614a89eadec3287e"

      def install
        bin.install "ortfodb_darwin_arm64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ortfo/db/releases/download/v1.4.0/ortfodb_Linux_x86_64.tar.gz"
      sha256 "d1c525f446f3db61a055b72a3ca2543d217d8e659857f443ec7e139d6aa7505d"

      def install
        bin.install "ortfodb_linux_amd64"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ortfo/db/releases/download/v1.4.0/ortfodb_Linux_arm64.tar.gz"
      sha256 "52317a64c1d85c0c91c374abc85ac742a9453a15835cb2327c98a1d6cc07e824"

      def install
        bin.install "ortfodb_linux_arm64"
      end
    end
  end

  def caveats
    <<~EOS
      Requires ffmpeg, ffprobe, gifsicle (for GIFs generation), pdftoppm (for PDF thumbnailing) and imagemagick to be on your PATH.
    EOS
  end
end
