# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ortfodb < Formula
  desc "A readable, easy and enjoyable way to manage portfolio databases using directories and text files."
  homepage "https://ortfo.org"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ortfo/db/releases/v1.3.0/ortfodb_Darwin_x86_64.tar.gz"
      sha256 "20160dd1c88bc422fc0c072c6bb0944e27b38a1196653de59eb36a2fe4cbcd83"

      def install
        bin.install "ortfodb_darwin_amd64"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ortfo/db/releases/v1.3.0/ortfodb_Darwin_arm64.tar.gz"
      sha256 "b0ec7bd58f9a4685a2bfa95165858cf6a98f659a9ea71538e5108235663ffc8d"

      def install
        bin.install "ortfodb_darwin_arm64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ortfo/db/releases/v1.3.0/ortfodb_Linux_x86_64.tar.gz"
      sha256 "fcd965cc99cc460d9c4a97a237727949b4e62c433778545daaf1f76ff5720046"

      def install
        bin.install "ortfodb_linux_amd64"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ortfo/db/releases/v1.3.0/ortfodb_Linux_arm64.tar.gz"
      sha256 "b9cca7971868e584dbe57178ce08c50727452d03c51011a4e2d5b117012602a8"

      def install
        bin.install "ortfodb_linux_arm64"
      end
    end
  end

  def caveats
    <<~EOS
      Requires ffmpeg, ffprobe, gifsicle (for GIFs generation), pdftoppm (for PDF thumbnailing) and imagemagick to be on your PATH.
    EOS
  end
end
