# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ortfodb < Formula
  desc "A readable, easy and enjoyable way to manage portfolio databases using directories and text files."
  homepage "https://ortfo.org"
  version "1.4.0"
  license "MIT"

  depends_on "ffmpeg"
  depends_on "gifsicle" => :optional
  depends_on "imagemagick"
  depends_on "poppler" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ortfo/db/releases/download/v1.4.0/ortfodb_Darwin_x86_64.tar.gz"
      sha256 "260edf1b8281ac8f1bfba904ae37d34b02dc94e00dbc306c46971f0b32677b4c"

      def install
        bin.install "ortfodb_darwin_amd64"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ortfo/db/releases/download/v1.4.0/ortfodb_Darwin_arm64.tar.gz"
      sha256 "5a4919e77a9a0f970960024cd839309d1f1f48607dc5bd999a539fa03488494a"

      def install
        bin.install "ortfodb_darwin_arm64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ortfo/db/releases/download/v1.4.0/ortfodb_Linux_x86_64.tar.gz"
      sha256 "b502f91958f65e764f3047fb5d6ba0f714390bb54979aae6dd8ab2e76f99d991"

      def install
        bin.install "ortfodb_linux_amd64"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ortfo/db/releases/download/v1.4.0/ortfodb_Linux_arm64.tar.gz"
      sha256 "968d65cfeb4f5b96e798da21d0fa902ed02256a3fb26fb845523a6ac38a6a8fa"

      def install
        bin.install "ortfodb_linux_arm64"
      end
    end
  end

  def caveats
    <<~EOS
      Requires ffmpeg, ffprobe, gifsicle (for GIFs generation), pdftoppm (for PDF thumbnailing) and imagemagick to be on your PATH.
    EOS
  end
end
